name: Build and update gitops repo

on:
  push:
    paths-ignore:
        - '.github/**'
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yaml

  get-short-sha:
    uses: ./.github/workflows/get-short-sha.yaml
    
  update-gitops-file:
    uses: ./.github/workflows/update-gitops-file.yaml
    with:
        image-sha: ${{ needs.get-short-sha.outputs.SHORT_SHA }}
    needs: [call-build-workflow, get-short-sha]
    
